# Generated by Django 5.1.2 on 2024-12-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('recommendation', 'おすすめ'), ('skewer', '串焼き'), ('onedish', '一品'), ('specialty', '名物'), ('friedfood', '揚げ物'), ('rice', 'ご飯'), ('dessert', 'デザート'), ('drink', 'ドリンク')], max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
